config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  get 'sessions/create'

  get 'sessions/destroy'

  resources :buildings, :except => [:new, :edit, :create]
  root :to => redirect('/buildings')
  get "filter" => "buildings#filter", as: 'filter'
  get "*path", to: redirect('/')  # Redirect invalid routes to home page.
  

end

app/models/building.rb
require 'net/http'

#:nodoc:
class Building < ActiveRecord::Base
  has_many :room

  def geo
    if lat && lng
      return { lat: lat, lng: lng }
    end

    query_gmap
  end

  private

  def query_gmap
    url = URI.parse("http://maps.googleapis.com/maps/api/geocode/json?\
                     key=#{ENV['GOOGLE_API_KEY']}&
                     address=${name}%20Hall%20Berkeley")
    req = Net::HTTP::Get.new(url.to_s)

    success = nil
    data = nil

    3.times.each do
      res = Net::HTTP.start(url.host, url.port) do |http|
        http.request(req)
      end
      data = JSON.parse res.body
      if data['status'] == 'OK'
        success = true
        break
      end
    end

    if success
      data['results'][0]['geometry']['location']
    else
      'Error'
    end
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :building
end

app/models/user.rb
class User < ActiveRecord::Base
    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.oauth_token = auth.credentials.token
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            user.save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  helper_method :filter_rooms
  helper_method :filter_by_capacity
  helper_method :filter_by_roomtype_1
  helper_method :filter_by_roomtype_2
  helper_method :filter_by_roomtype_3

  def index

  end

  def filter
    ret = []
    Building.all.includes(:room).each do |b|
      rooms = filter_rooms(b.room)
      next if rooms.empty?
      ret << ({
        id: b.id, name: b.name,
        geo: b.geo, # {lat: b.lat, lng: b.lng}
        count: rooms.count, 
        max: rooms.maximum(:capacity)
      })
    end
    render json: ret 
  end
  
  def search
  end
  
  def session_helper_user_id
      session[:user_id]
  end
  
  def show
    if session_helper_user_id == nil
      flash[:alert] = "Please log in."
      redirect_to buildings_path
      return
    end
    
    @rooms = filter_rooms
    building_id = params[:id] 
    @building = Building.find_by_id(building_id)
    
    if @building.blank?
      flash[:notice] = "This building does not exist."
      redirect_to buildings_path
    end

    @rooms = @rooms.where(:building_id => building_id).sort_by {|room| room.number.to_i}
    @rooms.each do |room|
      if room.misc == nil then room.misc = "N/A" end
      if room.facilities == nil then room.facilities = "N/A" end
    end
  end
  
  def filter_rooms(rooms = Room.all)
    if params[:StudentAccessible]
      rooms = rooms.where("UPPER(facilities) LIKE '%ADA-STUDENT%'")
    end
    if params[:Board]
      rooms = rooms.where("UPPER(facilities) LIKE '%BOARD%'")
    end
    if params[:AV]
      rooms = rooms.where("UPPER(facilities) LIKE '%AV%'")
    end
    
    rooms = filter_by_roomtype_1(rooms)
    rooms = filter_by_roomtype_2(rooms)
    rooms = filter_by_roomtype_3(rooms)
    
    filter_by_capacity(rooms)
  end
  
  def filter_by_roomtype_1(rooms)
    unless params[:Classroom]
      rooms = rooms.where("UPPER(misc) NOT LIKE '%CLASSROOM%'")
    end
    
    unless params[:LectureHall]
      rooms = rooms.where("UPPER(misc) NOT LIKE '%LECTURE%'")
    end
    
    rooms
  end
  
  def filter_by_roomtype_2(rooms)
    unless params[:Auditorium]
      rooms = rooms.where("UPPER(misc) NOT LIKE '%AUDITORIUM%'")
    end
    
    unless params[:SeminarRoom]
      rooms = rooms.where("UPPER(misc) NOT LIKE '%SEMINAR%'") 
    end
    
    rooms
  end
  
  def filter_by_roomtype_3(rooms)
    unless params[:OtherRooms]
      rooms = rooms.where("UPPER(misc) LIKE '%CLASSROOM%'
        OR UPPER(misc) LIKE '%LECTURE HALL%'
        OR UPPER(misc) LIKE '%AUDITORIUM%'
        OR UPPER(misc) LIKE '%SEMINAR ROOM%'")
    end
    rooms
  end
  
  def filter_by_capacity(rooms)
    if params[:capacityLower]
      rooms = rooms.where("capacity >= ?", params[:capacityLower].to_i)
    end
    if params[:capacityUpper]
      rooms = rooms.where("capacity <= ?", params[:capacityUpper].to_i)
    end
    rooms
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_helper
  end

  def destroy
    session[:user_id] = nil
    redirect_helper
  end
  
  def redirect_helper
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/buildings/index.html.haml
%div{:class => "panel-grout"}
  %div{:class => "panel panel-default"}
    %div{:class => "panel-heading"}
      %div
        %span
          %button{:class => "text-left", :"data-toggle" => "collapse", :"data-target" => "#filters_collapse", :id => "filter_btn"}
            %i{:class => "glyphicon glyphicon-resize-vertical"}
            Filter
        %span{:class => "tag label label-info", :id => "Classroom_tag", :style => "display: none"}
          %span Classroom
          %a
            %i{:class => "remove glyphicon glyphicon-remove glyphicon-white", :onclick => "remove_tag('Classroom')"}
        %span{:class => "tag label label-info", :id => "LectureHall_tag", :style => "display: none"}
          %span Lecture Hall
          %a
            %i{:class => "remove glyphicon glyphicon-remove glyphicon-white", :onclick => "remove_tag('LectureHall')"}
        %span{:class => "tag label label-info", :id => "Auditorium_tag", :style => "display: none"}
          %span Auditorium
          %a
            %i{:class => "remove glyphicon glyphicon-remove glyphicon-white", :onclick => "remove_tag('Auditorium')"}
        %span{:class => "tag label label-info", :id => "SeminarRoom_tag", :style => "display: none"}
          %span Seminar Room
          %a
            %i{:class => "remove glyphicon glyphicon-remove glyphicon-white", :onclick => "remove_tag('SeminarRoom')"}
        %span{:class => "tag label label-info", :id => "OtherRooms_tag", :style => "display: none"}
          %span Other Rooms
          %a
            %i{:class => "remove glyphicon glyphicon-remove glyphicon-white", :onclick => "remove_tag('OtherRooms')"}
        %span{:class => "tag label label-info", :id => "StudentAccessible_tag", :style => "display: none"}
          %span ADA-Student Accessible
          %a
            %i{:class => "remove glyphicon glyphicon-remove glyphicon-white", :onclick => "remove_tag('StudentAccessible')"}
        %span{:class => "tag label label-info", :id => "Board_tag", :style => "display: none"}
          %span Board
          %a
            %i{:class => "remove glyphicon glyphicon-remove glyphicon-white", :onclick => "remove_tag('Board')"}
        %span{:class => "tag label label-info", :id => "AV_tag", :style => "display: none"}
          %span AV Devices
          %a
            %i{:class => "remove glyphicon glyphicon-remove glyphicon-white", :onclick => "remove_tag('AV')"}
    %div{:id => "filters_collapse", :class => "panel-collapse collapse"}
      %div{:id => "filters_div", :class => "row"}
        = form_tag filter_path, :method => 'GET', :id => 'filters_form', :onsubmit => 'filter_update(event)' do
          %div{:class => "col-sm-1"}
          %div{:id => "roomtype_column", :class => "col-sm-3"}
            %h3{:class => "category_text"}Room Type
            %div{:class => "checkbox"}
              %label
                = check_box_tag "Classroom", true, params.fetch(:Classroom, false)
                Classroom
            %div{:class => "checkbox"}
              %label
                = check_box_tag "LectureHall", true, params.fetch(:LectureHall, false)
                Lecture Hall
            %div{:class => "checkbox"}
              %label
                = check_box_tag "Auditorium", true, params.fetch(:Auditorium, false)
                Auditorium
            %div{:class => "checkbox"}
              %label
                = check_box_tag "SeminarRoom", true, params.fetch(:SeminarRoom, false)
                Seminar Room
            %div{:class => "checkbox"}
              %label
                = check_box_tag "OtherRooms", true, params.fetch(:OtherRooms, false)
                Other Rooms
                
          %div{:id => "facilities_column", :class => "col-sm-3", :style => "margin-bottom: 40px"}
            %h3{:class => "category_text"}Features
            %div{:class => "checkbox"}
              %label
                = check_box_tag "StudentAccessible", true, params[:StudentAccessible]
                ADA-Student Accessible
            %div{:class => "checkbox"}
              %label
                = check_box_tag "Board", true, params[:Board]
                Board
            %div{:class => "checkbox"}
              %label
                = check_box_tag "AV", true, params[:AV]
                AV Devices
          
          %div{:id => "capacity_column", :class => "col-sm-3"}
            %h3{:class => "category_text", :style => "margin-left: 0px"}Capacity
            = number_field_tag "capacityLower", nil, min: 0, step: 1, class: "form-control", :style => "width: 100px; float: left", onchange: "limit()", value: params.fetch(:capacityLower, 0)
            %span{:id => "to-text"}
              TO
            = number_field_tag "capacityUpper", nil, min: 0, step: 1, class: "form-control", :style => "width: 100px; float: left", onchange: "limit()", value: params.fetch(:capacityUpper, 1000)
            
          %div{:class => "col-sm-2"}
            %button{:id => "filters-reset", :class => "btn btn-default", :onclick => "reset_filters()"}Reset
            %br
            %button{:id => "filters-submit", :class => "btn btn-default", :onclick => "filter_update(event)"}Show

#map

- @api = ENV['GOOGLE_API_KEY']
%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=#{@api}&callback=initMap"}

app/views/buildings/search.html.haml
%h1 Buildings#search
%p Find me in app/views/buildings/search.html.erb

app/views/buildings/show.html.erb
<div class="page-container">
  <div class="container">
    <div class="panel-grout">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div>
            <span>
              <button class="text-left" data-target="#filters_collapse" data-toggle="collapse" id="filter_btn">
                <i class="glyphicon glyphicon-resize-vertical"></i>
                Filter
              </button>
            </span>
            <span class="tag label label-info" id="Classroom_tag" style="display: none">
              <span>Classroom</span>
              <a>
                <i class="remove glyphicon glyphicon-remove glyphicon-white" onclick="details_remove_tag('Classroom')"></i>
              </a>
            </span>
            <span class="tag label label-info" id="LectureHall_tag" style="display: none">
              <span>Lecture Hall</span>
              <a>
                <i class="remove glyphicon glyphicon-remove glyphicon-white" onclick="details_remove_tag('LectureHall')"></i>
              </a>
            </span>
            <span class="tag label label-info" id="Auditorium_tag" style="display: none">
              <span>Auditorium</span>
              <a>
                <i class="remove glyphicon glyphicon-remove glyphicon-white" onclick="details_remove_tag('Auditorium')"></i>
              </a>
            </span>
            <span class="tag label label-info" id="SeminarRoom_tag" style="display: none">
              <span>Seminar Room</span>
              <a>
                <i class="remove glyphicon glyphicon-remove glyphicon-white" onclick="details_remove_tag('SeminarRoom')"></i>
              </a>
            </span>
            <span class="tag label label-info" id="OtherRooms_tag" style="display: none">
              <span>Other Rooms</span>
              <a>
                <i class="remove glyphicon glyphicon-remove glyphicon-white" onclick="details_remove_tag('OtherRooms')"></i>
              </a>
            </span>
            <span class="tag label label-info" id="StudentAccessible_tag" style="display: none">
              <span>ADA-Student Accessible</span>
              <a>
                <i class="remove glyphicon glyphicon-remove glyphicon-white" onclick="details_remove_tag('StudentAccessible')"></i>
              </a>
            </span>
            <span class="tag label label-info" id="Board_tag" style="display: none">
              <span>Board</span>
              <a>
                <i class="remove glyphicon glyphicon-remove glyphicon-white" onclick="details_remove_tag('Board')"></i>
              </a>
            </span>
            <span class="tag label label-info" id="AV_tag" style="display: none">
              <span>AV Devices</span>
              <a>
                <i class="remove glyphicon glyphicon-remove glyphicon-white" onclick="details_remove_tag('AV')"></i>
              </a>
            </span>
          </div>
        </div>
        <div class="panel-collapse collapse" id="filters_collapse">
          <div class="row" id="filters_div">
            <%= form_tag filter_path, :method => 'GET', :id => 'filters_form', :onsubmit => 'filterMarkers(event)' do %>
              <div class="col-sm-1"></div>
              <div class="col-sm-3" id="roomtype_column">
                <h3 class="category_text">Room Type</h3>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "Classroom", true, params.fetch(:Classroom, false) %>
                    Classroom
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "LectureHall", true, params.fetch(:LectureHall, false) %>
                    Lecture Hall
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "Auditorium", true, params.fetch(:Auditorium, false) %>
                    Auditorium
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "SeminarRoom", true, params.fetch(:SeminarRoom, false) %>
                    Seminar Room
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "OtherRooms", true, params.fetch(:OtherRooms, false) %>
                    Other Rooms
                  </label>
                </div>
              </div>
              <div class="col-sm-3" id="facilities_column" style="margin-bottom: 40px">
                <h3 class="category_text">Features</h3>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "StudentAccessible", true, params[:StudentAccessible] %>
                    ADA-Student Accessible
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "Board", true, params[:Board] %>
                    Board
                  </label>
                </div>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "AV", true, params[:AV] %>
                    AV Devices
                  </label>
                </div>
              </div>
              <div class="col-sm-3" id="capacity_column">
                <h3 class="category_text" style="margin-left: 0px">Capacity</h3>
                <%= number_field_tag "capacityLower", nil, min: 0, step: 1, class: "form-control", :style => "width: 100px; float: left", onchange: "limit()", value: params.fetch(:capacityLower, 0) %>
                <span id="to-text">
                  TO
                </span>
                <%= number_field_tag "capacityUpper", nil, min: 0, step: 1, class: "form-control", :style => "width: 100px; float: left", onchange: "limit()", value: params.fetch(:capacityUpper, 1000) %>
              </div>
              <div class="col-sm-2">
                <button class="btn btn-default" id="filters-reset" onclick="reset_filters()">Reset</button>
                <br/>
                <button class="btn btn-default" id="filters-submit" onclick="details_filter()">Show</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    
  

    <div class="row row-offcanvas row-offcanvas-left">
        
      <!-- sidebar -->
      <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
        <ul class="nav">
          <% @rooms.each do |room| %>
            <li style="text-align: center"><a href="#<%=room.number %>"> <%=@building.name %> <%=room.number %> </a></li>
          <% end %>
        </ul>
      </div>

      <!-- main area -->
      <% @rooms.each do |room| %>
              <div id="<%=room.number %>" class="tab-content" style="display:none, width: 75% !important"> 
                <h2> <%=@building.name %> <%=room.number %> </h2>
                <p>Capacity: <%=room.capacity %></p>
                <p>Room Type: <%=room.misc %></p>
                <p>Features: 
                    <ul class='features'>
                      <%room.facilities.split(',').each do |item| %>
                        <li> <%=item %></li>
                      <% end %>
                    </ul>
                </p>
              </div>
      <% end %>

    </div><!--/.row-->
  </div><!--/.container-->
</div><!--/.page-container-->

<script>
$(document).ready(function () {
$('.tab-content:not()').hide();
$('.col-xs-6.col-sm-3.sidebar-offcanvas ul li a').click(function (event) {
  event.preventDefault();
  var content = $(this).attr('href');
  $(this).parent().addClass('active');
  $(this).parent().siblings().removeClass('active');
  $(content).show();
  $(content).siblings('.tab-content').hide();
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Room Reservation</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/assets/stylesheets/application.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <!-- library -->
    <%= yield :library %>
  </head>
  <body>
    <!-- top navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
    	  <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#filter_div">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Room Reservation', buildings_path(request.query_parameters), :class => "navbar-brand" %>
          <% if current_user %>
            <ul class="nav navbar-nav navbar-right" style="float: right">
              <li><a><span class="glyphicon glyphicon-user"></span> Welcome, <%= current_user.name %></a></li>
              <li><a href="/signout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/auth/google_oauth2"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <div id="main">
      <% if flash[:alert] %>
        <div class="alert alert-danger alert" id="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <p style="font-size: 20px"><strong>Error:</strong> <%= flash[:alert]%>
          </p>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>